const LUGARES = [
  // === RESTAURANTES & BARES ===
  { id: 1,  nome: "Pé de Manga",          bairro: "Vila Madalena",      tipo: "BAR",          preco: "$$",   feito: false,
    descricao: "Bar charmoso em Vila Madalena com drinks autorais, petiscos criativos e uma vibe descontraída. Perfeito pra uma noite casual com boa música e boa companhia.",
    maps: "https://maps.google.com/?q=Pé+de+Manga+Vila+Madalena+São+Paulo",
    imagem: "https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?w=800&q=80",
    tiktok: "https://www.tiktok.com/embed/v2/7044178763491875078" },
  { id: 2,  nome: "Mata Citti",           bairro: "Pinheiros",           tipo: "RESTAURANTE",  preco: "$$$",  feito: false,
    descricao: "Restaurante sofisticado com cardápio autoral que mistura ingredientes brasileiros com técnicas contemporâneas. Ambiente íntimo e iluminação perfeita.",
    maps: "https://maps.google.com/?q=Mata+Citti+Pinheiros+São+Paulo",
    imagem: "https://images.unsplash.com/photo-1559339352-11d035aa65de?w=800&q=80",
    tiktok: "https://www.tiktok.com/embed/v2/7044178763491875078" },
  { id: 3,  nome: "Paris 6",              bairro: "Jardins",             tipo: "RESTAURANTE",  preco: "$$$",  feito: false,
    descricao: "Bistrô francês aberto 24h com clássicos como croque monsieur, fondue e fondant de chocolate. Ideal pra aniversários e ocasiões especiais.",
    maps: "https://maps.google.com/?q=Paris+6+Jardins+São+Paulo",
    imagem: "https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=800&q=80",
    tiktok: "https://www.tiktok.com/embed/v2/7044178763491875078",
    especial: "aniversário" },
  { id: 4,  nome: "Athenas Restaurante",  bairro: "Liberdade",           tipo: "RESTAURANTE",  preco: "$$",   feito: false,
    descricao: "Restaurante grego autêntico com pratos tradicionais como gyros, souvlaki e baklava. Uma viagem à Grécia sem sair de SP.",
    maps: "https://maps.google.com/?q=Athenas+Restaurante+São+Paulo",
    imagem: "https://images.unsplash.com/photo-1544025162-d76694265947?w=800&q=80",
    tiktok: "https://www.tiktok.com/embed/v2/7044178763491875078" },
  { id: 5,  nome: "Coco Bambu",           bairro: "Moema",               tipo: "RESTAURANTE",  preco: "$$$",  feito: false,
    descricao: "Clássico da culinária nordestina com frutos do mar frescos, lagosta e moquecas. Porções generosas e ambiente animado.",
    maps: "https://maps.google.com/?q=Coco+Bambu+Moema+São+Paulo",
    imagem: "https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=800&q=80",
    tiktok: "https://www.tiktok.com/embed/v2/7044178763491875078" },
  { id: 6,  nome: "Vila Hermosa Bistro",  bairro: "Vila Mariana",        tipo: "RESTAURANTE",  preco: "$$",   feito: false,
    descricao: "Bistrô aconchegante com cardápio variado, vinhos bem selecionados e ambiente charmoso. Ótimo custo-benefício pra um jantar especial.",
    maps: "https://maps.google.com/?q=Vila+Hermosa+Bistro+Vila+Mariana+São+Paulo",
    imagem: "https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=800&q=80",
    tiktok: "https://www.tiktok.com/embed/v2/7044178763491875078" },
  { id: 7,  nome: "Quintal do Bardo",     bairro: "Perdizes",            tipo: "BAR",          preco: "$$",   feito: false,
    descricao: "Bar ao ar livre com shows ao vivo, chope gelado e petiscos clássicos. O quintal que todo mundo quer ter. Clima de fim de tarde perfeito.",
    maps: "https://maps.google.com/?q=Quintal+do+Bardo+Perdizes+São+Paulo",
    imagem: "https://images.unsplash.com/photo-1572116469696-31de0f17cc34?w=800&q=80",
    tiktok: "https://www.tiktok.com/embed/v2/7044178763491875078" },
  { id: 8,  nome: "Round 2",              bairro: "Pinheiros",           tipo: "BAR",          preco: "$$",   feito: false,
    descricao: "Bar temático de games com fliperama, drinks nerds e muito nostalgia. Pra quem quer beber e ainda ganhar no Street Fighter.",
    maps: "https://maps.google.com/?q=Round+2+Bar+Pinheiros+São+Paulo",
    imagem: "https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=800&q=80",
    tiktok: "https://www.tiktok.com/embed/v2/7044178763491875078" },
  { id: 9,  nome: "Tata Sushi",           bairro: "Moema",               tipo: "ASIÁTICO",     preco: "$$",   feito: false,
    descricao: "Sushi de qualidade com ambiente descontraído. Combinados criativos, temakis generosos e um atendimento que faz você voltar toda semana.",
    maps: "https://maps.google.com/?q=Tata+Sushi+Moema+São+Paulo",
    imagem: "https://images.unsplash.com/photo-1617196034183-421b4040ed20?w=800&q=80",
    tiktok: "https://www.tiktok.com/embed/v2/7044178763491875078" },
  { id: 10, nome: "Yum Sushi",            bairro: "Liberdade",           tipo: "ASIÁTICO",     preco: "$$",   feito: false,
    descricao: "Rodízio japonês tradicional no coração da Liberdade. Pratos caprichados, temakis frescos e ambiente autêntico.",
    maps: "https://maps.google.com/?q=Yum+Sushi+Liberdade+São+Paulo",
    imagem: "https://images.unsplash.com/photo-1611143669185-af224c5e3252?w=800&q=80",
    tiktok: "https://www.tiktok.com/embed/v2/7044178763491875078" },
  { id: 11, nome: "Terraço Jardins",      bairro: "Jardins",             tipo: "ROOFTOP",      preco: "$$$",  feito: false,
    descricao: "Rooftop sofisticado com vista privilegiada dos Jardins, drinks elaborados e cardápio executivo. O lugar certo pra impressionar.",
    maps: "https://maps.google.com/?q=Terraço+Jardins+São+Paulo",
    imagem: "https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800&q=80",
    tiktok: "https://www.tiktok.com/embed/v2/7044178763491875078" },
  { id: 12, nome: "Lucido Bar",           bairro: "Vila Madalena",       tipo: "BAR",          preco: "$$",   feito: false,
    descricao: "Bar minimalista com cocktails bem-elaborados e playlist impecável. Um dos queridinhos da Vila Madalena pra quem curte uma noite mais intimista.",
    maps: "https://maps.google.com/?q=Lucido+Bar+Vila+Madalena+São+Paulo",
    imagem: "https://images.unsplash.com/photo-1551024709-8f23befc6f87?w=800&q=80",
    tiktok: "https://www.tiktok.com/embed/v2/7044178763491875078" },
  { id: 13, nome: "Café Girondino",       bairro: "Centro Histórico",    tipo: "CAFÉ",         preco: "$",    feito: false,
    descricao: "Café histórico fundado em 1887 no coração do Centro. Ambiente vintage, café coado na hora e salgados que viram lenda. Patrimônio de SP.",
    maps: "https://maps.google.com/?q=Café+Girondino+Centro+São+Paulo",
    imagem: "https://images.unsplash.com/photo-1445116572660-236099ec97a0?w=800&q=80",
    tiktok: "https://www.tiktok.com/embed/v2/7044178763491875078" },
  { id: 14, nome: "Sorvete de Pudim",     bairro: "Pinheiros",           tipo: "CAFÉ",         preco: "$",    feito: false,
    descricao: "Sorveteria artesanal especializada no icônico sorvete de pudim com calda de caramelo. Simples, indulgente e perfeito pra qualquer hora.",
    maps: "https://maps.google.com/?q=Sorvete+de+Pudim+Pinheiros+São+Paulo",
    imagem: "https://images.unsplash.com/photo-1501443762994-82bd5dace89a?w=800&q=80",
    tiktok: "https://www.tiktok.com/embed/v2/7044178763491875078" },

  // === EXPERIÊNCIAS ===
  { id: 15, nome: "Templo de Ribeirão Pires", bairro: "Ribeirão Pires", tipo: "CULTURA",     preco: "$",    feito: false,
    descricao: "Templo budista gigante a 40km de SP, com estátua de Buda de 12m, jardins impecáveis e uma paz que você não esperava sentir tão perto de casa.",
    maps: "https://maps.google.com/?q=Templo+Zu+Lai+Ribeirão+Pires",
    imagem: "https://images.unsplash.com/photo-1528360983277-13d401cdc186?w=800&q=80",
    tiktok: "https://www.tiktok.com/embed/v2/7044178763491875078" },
  { id: 16, nome: "Cabine Fotográfica",   bairro: "Vila Madalena",       tipo: "EXPERIÊNCIA",  preco: "$",    feito: false,
    descricao: "Cabines fotográficas analógicas espalhadas pela cidade — aquele registro vintage que fica pra sempre. Procure as da Vila Madalena e do Bom Retiro.",
    maps: "https://maps.google.com/?q=cabine+fotográfica+Vila+Madalena+São+Paulo",
    imagem: "https://images.unsplash.com/photo-1570698473787-5063dc86c1d8?w=800&q=80",
    tiktok: "https://www.tiktok.com/embed/v2/7044178763491875078" },
  { id: 17, nome: "Feira de Embu das Artes", bairro: "Embu das Artes",   tipo: "MERCADO",      preco: "$",    feito: false,
    descricao: "Uma das maiores feiras de artesanato do Brasil, todo fim de semana. Arte, culinária regional, antiguidades e muito charme numa cidade histórica a 27km de SP.",
    maps: "https://maps.google.com/?q=Feira+Embu+das+Artes",
    imagem: "https://images.unsplash.com/photo-1488459716781-31db52582fe9?w=800&q=80",
    tiktok: "https://www.tiktok.com/embed/v2/7044178763491875078" },
  { id: 18, nome: "Aquário de São Paulo", bairro: "Santo André",         tipo: "CULTURA",      preco: "$$",   feito: false,
    descricao: "O maior aquário da América Latina com mais de 3.000 animais. Tubarões, arraias, lontras e um túnel subaquático que parece outro mundo.",
    maps: "https://maps.google.com/?q=Aquário+de+São+Paulo",
    imagem: "https://images.unsplash.com/photo-1559827291-72ee739d0d9a?w=800&q=80",
    tiktok: "https://www.tiktok.com/embed/v2/7044178763491875078" },
  { id: 19, nome: "SESC Pompeia",         bairro: "Pompeia",             tipo: "CULTURA",      preco: "$",    feito: false,
    descricao: "Projeto arquitetônico de Lina Bo Bardi que é patrimônio cultural. Teatro, exposições, esportes, restaurante e uma libraria incrível. Explorar tudo leva o dia.",
    maps: "https://maps.google.com/?q=SESC+Pompeia+São+Paulo",
    imagem: "https://images.unsplash.com/photo-1568605114967-8130f3a36994?w=800&q=80",
    tiktok: "https://www.tiktok.com/embed/v2/7044178763491875078" },
  { id: 20, nome: "Festival de Lanternas", bairro: "São Paulo",          tipo: "EXPERIÊNCIA",  preco: "$$",   feito: false,
    descricao: "Instalações luminosas gigantes espalhadas pelo espaço. Lanternas chinesas, esculturas de luz e aquela magia de caminhar no escuro iluminado de cores.",
    maps: "https://maps.google.com/?q=Festival+Lanternas+São+Paulo",
    imagem: "https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=800&q=80",
    tiktok: "https://www.tiktok.com/embed/v2/7044178763491875078" },

  // === VIAGENS ===
  { id: 21, nome: "Ilha Bela",            bairro: "Litoral Norte SP",    tipo: "VIAGEM",       preco: "$$",   feito: false,
    descricao: "A ilha mais bonita do litoral paulista — praias de água transparente, cachoeiras na mata, trilhas e uma vibe de ilha mesmo. Bate-volta ou fim de semana completo.",
    maps: "https://maps.google.com/?q=Ilhabela+São+Paulo",
    imagem: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800&q=80",
    tiktok: "https://www.tiktok.com/embed/v2/7044178763491875078" },
  { id: 22, nome: "Pôr do Sol — Sto. Antônio do Pinhal", bairro: "Serra da Mantiqueira", tipo: "VIAGEM", preco: "$", feito: false,
    descricao: "Cidadezinha serrana a 200km de SP com o pôr do sol mais bonito da Mantiqueira. Campos de lavanda, clima fresco e aquela sensação de fim de mundo (boa).",
    maps: "https://maps.google.com/?q=Santo+Antônio+do+Pinhal",
    imagem: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&q=80",
    tiktok: "https://www.tiktok.com/embed/v2/7044178763491875078" },
  { id: 23, nome: "Curitiba",             bairro: "Paraná",              tipo: "VIAGEM",       preco: "$$",   feito: false,
    descricao: "A capital mais fria e organizada do Brasil. Jardim Botânico, Ópera de Arame, Museu Oscar Niemeyer e uma cena gastronômica surpreendente. 4h de carro de SP.",
    maps: "https://maps.google.com/?q=Curitiba+Paraná",
    imagem: "https://images.unsplash.com/photo-1548681528-6a5c45b66b42?w=800&q=80",
    tiktok: "https://www.tiktok.com/embed/v2/7044178763491875078" },
  { id: 24, nome: "Holambra",             bairro: "Interior SP",         tipo: "VIAGEM",       preco: "$",    feito: false,
    descricao: "A cidade das flores holandesas no interior de SP. Campos de tulipas, moinhos de vento, arquitetura europeia e o Festival Expoflora. Um dia diferente de tudo.",
    maps: "https://maps.google.com/?q=Holambra+São+Paulo",
    imagem: "https://images.unsplash.com/photo-1490750967868-88df5691cc8b?w=800&q=80",
    tiktok: "https://www.tiktok.com/embed/v2/7044178763491875078" },
  { id: 25, nome: "JAPÃO 🗾",             bairro: "Ásia",                tipo: "VIAGEM",       preco: "$$$$", feito: false,
    descricao: "O sonho grande. Tóquio, Kyoto, Osaka, Nara. Templos shinto, ramen de verdade, cerejeiras na primavera, lojas de anime e aquele silêncio que só o Japão tem. Um dia.",
    maps: "https://maps.google.com/?q=Japão",
    imagem: "https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?w=800&q=80",
    tiktok: "https://www.tiktok.com/embed/v2/7044178763491875078",
    especial: "sonho grande" }
];

const TIPOS = ["TODOS", "RESTAURANTE", "BAR", "ASIÁTICO", "CAFÉ", "ROOFTOP", "CULTURA", "MERCADO", "EXPERIÊNCIA", "VIAGEM"];
